name: Risoto de Morango
favicon: null
layout_spectrum: 0.6279675557743758
typography_spectrum: 0.3155129214283079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7456125672906637
  lightness: 0.35340276500210166
  saturation: 0.8909151637926698
  rhythmicContrast: 0.29317152104340494
purpose: []
