name: Risoto de Morango
favicon: null
layout_spectrum: 0.29078
typography_spectrum: 0.49663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#b5b88d'
    - '#676668'
    - '#a51c1e'
    - '#35aba3'
  brandStrength: 0.7456125672906637
  lightness: 0.35340276500210166
  saturation: 0.8909151637926698
  rhythmicContrast: 0.29317152104340494
purpose: []
